version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - duncanmcclean
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.28.1
    - 8.31.0
    - 8.36.1
    - 8.36.2
  - dependency-name: barryvdh/laravel-debugbar
    versions:
    - 3.5.2
  - dependency-name: sentry/sentry-laravel
    versions:
    - 2.3.1
